### ISSUE TITLE
这个项目还维护吗？ 

### ISSUE THREAD

**Issue by osdebianly** [zgldh/workerboy#2]
- 安装完成之后，没法正常运行, cpu 100%
- [gateway](http://www.workerman.net/last_update) 还未升级到2.0

**Comment by zgldh** [comment]
水平有限不维护了。 ![装逼](http://zhuangbi.idagou.com/i/2015-06-27-d0c7aee2e0b7fec7aad2d01f083803e4.jpg?imageView2/0/h/80)

**Comment by jinchunguang** [comment]
坚持吧,骚年,我很期待,66个赞

**Comment by zgldh** [comment]
思路是提供一个 workman 和 Laravel 互相通信的办法。 
一般来说要靠共享缓存系统来握手，然后互相存一下 session id 和 client id
但水平和精力有限就不维护了。 集中精神搞 VueJS 去了。

**Comment by osdebianly** [comment]
好的，gateway 增加了[bindUid](http://workerman.net/gatewaydoc/gateway-worker-development/bind-uid.html)

2016-05-24 18:57 GMT+08:00 zgldh notifications@github.com:
