### ISSUE TITLE
can not mkdir()

### ISSUE THREAD

**Issue by cqiuer** [zgldh/workerboy#4]
大神你好，我这个有权限但是他还是报那个无法创建文件夹 我看那个file类里就接收不到 store_config的参数，一个参数都没有。你看这个是什么问题？

**Comment by zgldh** [comment]
这个库废弃了。 和web框架结合请看这里 http://workerman.net/gatewaydoc/work-with-other-frameworks/README.html

但看你遇到的情况，可能是文件owner的问题。 或者你检查下PHP的运行用户组，webserver的运行用户组。

**Comment by cqiuer** [comment]
谢谢大神！我们用了workerman和gatewayworker。很感谢您的贡献！






在 2017-12-12 18:37:59，"zgldh" <notifications@github.com> 写道：


这个库废弃了。 和web框架结合请看这里 http://workerman.net/gatewaydoc/work-with-other-frameworks/README.html

但看你遇到的情况，可能是文件owner的问题。 或者你检查下PHP的运行用户组，webserver的运行用户组。
